name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Security Tools
        run: |
          pip install bandit safety

      - name: Run SAST Scan (Bandit)
        run: |
          bandit -r .
        continue-on-error: true

      - name: Run Dependency Scan (Safety)
        run: |
          safety check
        continue-on-error: true